# Generated by Django 3.0.5 on 2022-04-29 22:27

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('people_related', models.PositiveIntegerField()),
                ('percentage_per_person', models.FloatField()),
            ],
            options={
                'verbose_name': 'Commission agent',
                'verbose_name_plural': 'Commission agents',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_payment', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('next_payment', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField()),
                ('last_order_date', models.DateField()),
                ('n_projects', models.PositiveIntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ProjectByInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_trees', models.PositiveIntegerField()),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('next_payment', models.DateField()),
                ('coordinates', models.CharField(max_length=50)),
                ('co2_consumption', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('active', models.BooleanField(default=True)),
                ('commission_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_commission_agent', to='account.CommissionAgent')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investor', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Project by investor',
                'verbose_name_plural': 'Projects by investor',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Visitor'), (2, 'One Time Investment'), (3, 'Subscription Investment'), (4, 'Admin')], null=True)),
                ('country', django_countries.fields.CountryField(default='Co', max_length=2)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('adress', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('rut', models.CharField(default='', max_length=100, unique=True)),
                ('tax_register', models.CharField(default='', max_length=50)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('web_domine', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
