# Generated by Django 3.0.5 on 2022-03-03 14:30

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('account', '0004_auto_20220303_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('people_related', models.PositiveIntegerField()),
                ('percentage_per_person', models.FloatField()),
            ],
            options={
                'verbose_name': 'Commission agent',
                'verbose_name_plural': 'Commission agents',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_payment', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('next_payment', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField()),
                ('last_order_date', models.DateField()),
                ('n_projects', models.PositiveIntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ProjectByInvestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_trees', models.PositiveIntegerField()),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('next_payment', models.DateField()),
                ('coordinates', models.CharField(max_length=50)),
                ('co2_consumption', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('active', models.BooleanField(default=True)),
                ('commission_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_commission_agent', to='account.CommissionAgent')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investor', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Project by investor',
                'verbose_name_plural': 'Projects by investor',
            },
        ),
    ]
