# Generated by Django 3.0.5 on 2022-03-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220303_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unique_payment',
        ),
    ]
