# Generated by Django 3.0.5 on 2023-02-23 21:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nombre', models.CharField(max_length=150)),
                ('comprador_id', models.CharField(max_length=150)),
                ('comprador_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comprador_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('beneficiario_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('beneficiario_id', models.CharField(blank=True, max_length=150, null=True)),
                ('beneficiario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('beneficiario_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address_line_1', models.CharField(max_length=150)),
                ('address_line_2', models.CharField(blank=True, max_length=150, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, null=True)),
                ('default', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='projects.Bill')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('plat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_trees', models.PositiveIntegerField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('stripe_price_id', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('coordinates', models.CharField(blank=True, max_length=120, null=True)),
                ('geokml', models.FileField(blank=True, null=True, upload_to='poligonos/')),
                ('reg_forestal', models.FileField(blank=True, null=True, upload_to='registros_forestales/')),
                ('resena', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('n_trees', models.PositiveIntegerField()),
                ('plantation_date', models.DateField()),
                ('inicioventa_date', models.DateField()),
                ('corte_date', models.DateField()),
                ('total_invested', models.FloatField()),
                ('total_unit_initial', models.FloatField()),
                ('ica_register', models.CharField(blank=True, max_length=120, null=True)),
                ('n_hectares', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('trees_left', models.PositiveIntegerField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, max_length=120, null=True)),
                ('payment_collection', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects', verbose_name='Imagen')),
                ('price_onepayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_onepayment', to='projects.Pricing')),
                ('price_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_subscription', to='projects.Pricing')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('n_projects', models.PositiveIntegerField()),
                ('next_payment', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Tipoarbol',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_tree', models.ImageField(blank=True, null=True, upload_to='images/projects', verbose_name='Imagen del arbol')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='images/projects', verbose_name='Imagen del fondo')),
                ('especie', models.CharField(blank=True, max_length=120, null=True, verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Tipo de arbol',
                'verbose_name_plural': 'Tipos de arbol',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_id', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.Pricing')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.Subscription')),
            ],
            options={
                'verbose_name': 'Subscription Element',
                'verbose_name_plural': 'Subscription Elements',
            },
        ),
        migrations.CreateModel(
            name='Rentabilidad',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Rentabilidad',
                'verbose_name_plural': 'Rentabilidades',
            },
        ),
        migrations.CreateModel(
            name='ProjectTrackingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heigth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dch', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('captured_co2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('age', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('record_date', models.DateField()),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Plat')),
            ],
            options={
                'verbose_name': 'Project record',
                'verbose_name_plural': 'Project records',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tipoarbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.Tipoarbol'),
        ),
        migrations.AddField(
            model_name='plat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.CreateModel(
            name='PercentageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(unique=True)),
                ('growth_avg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dch_avg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume_growth_avg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('growth_pctg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dch_pctg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume_growth_pctg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_unit_current', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('profitability', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('project_value', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Percentage record',
                'verbose_name_plural': 'Percentage records',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('type_inversion', models.CharField(choices=[('M', 'Suscripción mensual'), ('O', 'Pago único')], default='M', max_length=1, verbose_name='Inversion type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Vendedor'),
        ),
    ]
