# Generated by Django 3.1.7 on 2021-03-16 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('plat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_trees', models.PositiveIntegerField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('coordinates', models.CharField(max_length=120)),
                ('n_trees', models.PositiveIntegerField()),
                ('plantation_date', models.DateField()),
                ('total_invested', models.FloatField()),
                ('total_unit_initial', models.FloatField()),
                ('tree_type', models.CharField(max_length=120)),
                ('n_hectares', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('trees_left', models.PositiveIntegerField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, max_length=120, null=True)),
                ('payment_collection', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTrackingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heigth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dch', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('captured_co2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('age', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('record_date', models.DateField()),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plat')),
            ],
            options={
                'verbose_name': 'Project record',
                'verbose_name_plural': 'Project records',
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='PercentageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(unique=True)),
                ('growth_avg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dch_avg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume_growth_avg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('growth_pctg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dch_pctg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('volume_growth_pctg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_unit_current', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('profitability', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('project_value', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Percentage record',
                'verbose_name_plural': 'Percentage records',
            },
        ),
    ]
