# Generated by Django 3.0.5 on 2022-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='type_inversion',
            field=models.CharField(choices=[('M', 'Monthly subscription'), ('O', 'One payment')], default='M', max_length=1, verbose_name='Inversion type'),
        ),
    ]
