# Generated by Django 3.0.5 on 2022-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ica_register',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
